# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ":boom: Breaking changes"
    labels:
      - breaking
  - title: ğŸš¨ Removed
    label: removed
  - title: ":tada: Major features and improvements"
    labels:
      - major-enhancement
      - major-rfe
  - title: ğŸ› Major bug fixes
    labels:
      - major-bug
  - title: âš ï¸ Deprecated
    label: deprecated
  - title: ğŸš€ New features and improvements
    labels:
      - enhancement
      - feature
      - rfe
  - title: ğŸ› Bug Fixes
    labels:
      - bug
      - Bug
      - fix
      - bugfix
      - regression
  - title: ":construction_worker: Changes for plugin developers"
    labels:
      - developer
  # Default label used by Dependabot
  - title: ğŸ“¦ Dependency updates
    label: dependencies
  - title: ğŸ“ Documentation updates
    label: documentation
  - title: ğŸ‘» Maintenance
    labels:
      - chore
      - internal
      - Build
      - build
  - title: ğŸš¦ Tests
    labels:
      - test
      - tests
      - Test
      - Tests
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
# Disable certain characters in title from being interpreted as markdown
change-title-escapes: '\<*_&#'

template: |
  <!-- Optional: add a release summary here -->
  $CHANGES
